tasks: make robust to accept empty body (#5332)
**Which issue(s) this PR fixes**: 
Fixes #

**What this PR does / why we need it**: 

In the previous backporter, it assumes that
PR template was filled in pull request body,
but there was a case that it does not satisfy it in practical use case
(fix a typo).

It will fix the following error:

```
  NoMethodError: undefined method 'gsub' for nil (NoMethodError)
            body = pull_request["body"].gsub(/\*\*Which issue\(s\) this PR fixes\*\*: \r\n/,
                                       ^^^^^
```

**Docs Changes**:

N/A

**Release Note**: 

N/A

Signed-off-by: Kentaro Hayashi <hayashi@clear-code.com>